// <auto-generated />
using System;
using System.Collections.Generic;
using Azoxia.AdaIsAkademi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Azoxia.AdaIsAkademi.Persistence.Migrations
{
    [DbContext(typeof(AdaIsAkademiDbContext))]
    [Migration("20260505225319_AddWorkerProfileBioSocialAndMediaKeys")]
    partial class AddWorkerProfileBioSocialAndMediaKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.CommissionAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int?>("CommissionReceivableId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnOrder(5);

                    b.Property<string>("Note")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnOrder(7);

                    b.Property<int?>("WorkerPayoutId")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Azoxia.AdaIsAkademi.Domain.CommissionAuditLog.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CommissionReceivableId");

                    b.HasIndex("WorkerPayoutId");

                    b.HasIndex("EmployerId", "CreatedAt");

                    b.ToTable("CommissionAuditLog", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.CommissionReceivable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnOrder(3);

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnOrder(2);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Azoxia.AdaIsAkademi.Domain.CommissionReceivable.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("Currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EmployerId", "PeriodStart", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("CommissionReceivable", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(7);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(11);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(12);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(10);

                    b.Property<string>("LogoObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(8);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(9);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Azoxia.AdaIsAkademi.Domain.Employer.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("District")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address_District");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Address_Line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Address_PostalCode");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "Azoxia.AdaIsAkademi.Domain.Employer.Contact#Contact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Contact_Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_LastName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Contact_Phone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TaxNumber", "Azoxia.AdaIsAkademi.Domain.Employer.TaxNumber#TaxNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("TaxNumber");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.ToTable("Employer", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.EmployerLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(5);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(6);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(10);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(11);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("GeofenceRadiusMetres")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(8);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "Azoxia.AdaIsAkademi.Domain.EmployerLocation.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("District")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address_District");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Address_Line2");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Address_PostalCode");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "Azoxia.AdaIsAkademi.Domain.EmployerLocation.Contact#Contact", b1 =>
                        {
                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Contact_Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_LastName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Contact_Phone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Coordinate", "Azoxia.AdaIsAkademi.Domain.EmployerLocation.Coordinate#GeoCoordinate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Coordinate_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Coordinate_Longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployerId");

                    b.HasIndex("Name");

                    b.ToTable("EmployerLocation", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<int>("JobPostingId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnOrder(5);

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnOrder(6);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "WorkerId")
                        .IsUnique();

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("JobApplication", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(10);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(1);

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("JobCategory", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(12);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(13);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(17);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(18);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnOrder(5);

                    b.PrimitiveCollection<float[]>("DescriptionEmbedding")
                        .HasColumnType("real[]")
                        .HasColumnOrder(11);

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("EmployerLocationId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("HeadCount")
                        .HasColumnType("integer")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(16);

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnOrder(6);

                    b.Property<TimeOnly>("ShiftEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnOrder(8);

                    b.Property<TimeOnly>("ShiftStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnOrder(7);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(10);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(14);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(15);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Wage", "Azoxia.AdaIsAkademi.Domain.JobPosting.Wage#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("WageAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("WageCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("EmployerId", "Status");

                    b.HasIndex("EmployerLocationId", "ShiftDate");

                    b.ToTable("JobPosting", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobPostingSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnOrder(2);

                    b.Property<int>("JobPostingId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tag", "Azoxia.AdaIsAkademi.Domain.JobPostingSkill.Tag#SkillTag", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Tag");
                        });

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobPostingSkill", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.OverdueJobAlarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AlarmDate")
                        .HasColumnType("date")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<int>("JobPostingId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("AlarmDate");

                    b.HasIndex("JobPostingId", "AlarmDate")
                        .IsUnique();

                    b.ToTable("OverdueJobAlarm", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(10);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(1);

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnomalyCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.Property<string>("CheckInTokenHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(8);

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsAnomalyFlagged")
                        .HasColumnType("boolean");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("JobPostingId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(6);

                    b.Property<string>("SupervisorCheckInTokenHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset?>("SupervisorCheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(10);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId")
                        .IsUnique();

                    b.HasIndex("JobPostingId");

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("ShiftAssignment", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.ShiftSupervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnOrder(4);

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SystemUserId");

                    b.HasIndex("EmployerId", "SystemUserId");

                    b.ToTable("ShiftSupervisor", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(16);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(17);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(21);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(22);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(14);

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(13);

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(15);

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnOrder(9);

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(20);

                    b.Property<DateTimeOffset?>("LastFailedLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(10);

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(7);

                    b.Property<DateTimeOffset?>("LastPasswordChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(12);

                    b.Property<DateTimeOffset?>("LastSuccessfulLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(11);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(3);

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnOrder(8);

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(18);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(19);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SystemUser", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(5);

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId", "DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("SystemUserDevice", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(7);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(11);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(12);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnOrder(4);

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(8);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.ToTable("SystemUserGroup", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnOrder(5);

                    b.Property<int?>("ScopeId")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("SystemUserGroupId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.HasIndex("SystemUserGroupId", "SystemUserId", "ScopeType", "ScopeId");

                    b.ToTable("SystemUserGroupMembership", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Effect")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("SystemUserGroupId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SystemUserGroupId", "PermissionId")
                        .IsUnique();

                    b.ToTable("SystemUserGroupPermission", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserNotificationDispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnOrder(8);

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(12);

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(10);

                    b.Property<string>("FallbackReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(9);

                    b.Property<int?>("JobPostingId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(13);

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnOrder(11);

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(14);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(5);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnOrder(6);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(7);

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("SystemUserId", "Status");

                    b.HasIndex("WorkerId", "Status", "CreatedAt");

                    b.ToTable("SystemUserNotificationDispatch", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnOrder(5);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SystemUserId", "DeviceId");

                    b.HasIndex("SystemUserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("SystemUserRefreshToken", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(12);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(13);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(17);

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(18);

                    b.Property<DateTimeOffset?>("EmbeddingUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.Property<decimal?>("ExpectedSalaryMaxAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnOrder(10);

                    b.Property<string>("ExpectedSalaryMaxCurrency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnOrder(11);

                    b.Property<decimal?>("ExpectedSalaryMinAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnOrder(8);

                    b.Property<string>("ExpectedSalaryMinCurrency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnOrder(16);

                    b.Property<string>("Nationality")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnOrder(4);

                    b.Property<string>("ProfilePhotoObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.PrimitiveCollection<float[]>("SkillEmbedding")
                        .HasColumnType("real[]")
                        .HasColumnOrder(6);

                    b.Property<int>("SystemUserId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("University")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(5);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(14);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SystemUserId")
                        .IsUnique();

                    b.ToTable("Worker", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnOrder(3);

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnOrder(4);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "DayOfWeek");

                    b.ToTable("WorkerAvailability", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnOrder(6);

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnOrder(5);

                    b.Property<DateOnly>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerCertificate", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.Property<int>("EducationType")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnOrder(6);

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("boolean")
                        .HasColumnOrder(7);

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnOrder(5);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerEducation", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnOrder(6);

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnOrder(5);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnOrder(4);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerExperience", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerInterestedJobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("WorkerId", "JobCategoryId")
                        .IsUnique();

                    b.ToTable("WorkerInterestedJobCategory", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnOrder(2);

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "Language")
                        .IsUnique();

                    b.ToTable("WorkerLanguage", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("ConfirmationDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(8);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(10);

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnOrder(11);

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(9);

                    b.Property<DateTimeOffset?>("ProcessingMarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnOrder(5);

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CommissionAmount", "Azoxia.AdaIsAkademi.Domain.WorkerPayout.CommissionAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CommissionAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("CommissionCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GrossAmount", "Azoxia.AdaIsAkademi.Domain.WorkerPayout.GrossAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("GrossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("GrossCurrency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NetAmount", "Azoxia.AdaIsAkademi.Domain.WorkerPayout.NetAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("NetAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("NetCurrency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.HasIndex("EmployerId", "Status");

                    b.HasIndex("WorkerId", "Status");

                    b.ToTable("WorkerPayout", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(2);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnOrder(3);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "Azoxia.AdaIsAkademi.Domain.WorkerReference.Contact#Contact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("Contact_Email");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Contact_LastName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Contact_Phone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerReference", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tag", "Azoxia.AdaIsAkademi.Domain.WorkerSkill.Tag#SkillTag", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Tag");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerSkill", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerSocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnOrder(3);

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "Platform")
                        .IsUnique();

                    b.ToTable("WorkerSocialLink", (string)null);
                });

            modelBuilder.Entity("Azoxia.Core.Persistence.DbLogging.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Exception")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("UtcTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UtcTimestamp");

                    b.ToTable("AppLogs", (string)null);
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.CommissionAuditLog", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.ShiftAssignment", "ShiftAssignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.CommissionReceivable", "CommissionReceivable")
                        .WithMany()
                        .HasForeignKey("CommissionReceivableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.WorkerPayout", "WorkerPayout")
                        .WithMany()
                        .HasForeignKey("WorkerPayoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissionReceivable");

                    b.Navigation("Employer");

                    b.Navigation("ShiftAssignment");

                    b.Navigation("WorkerPayout");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.CommissionReceivable", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.EmployerLocation", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany("Locations")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobApplication", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobCategory", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobPosting", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany("JobPostings")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.EmployerLocation", "EmployerLocation")
                        .WithMany()
                        .HasForeignKey("EmployerLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("EmployerLocation");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobPostingSkill", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobPosting", "JobPosting")
                        .WithMany("Skills")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.OverdueJobAlarm", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Permission", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Permission", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.ShiftAssignment", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("JobPosting");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.ShiftSupervisor", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany("Supervisors")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.EmployerLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Location");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserDevice", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany("Devices")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroupMembership", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUserGroup", "SystemUserGroup")
                        .WithMany()
                        .HasForeignKey("SystemUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");

                    b.Navigation("SystemUserGroup");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroupPermission", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUserGroup", "SystemUserGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("SystemUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("SystemUserGroup");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserNotificationDispatch", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JobPosting");

                    b.Navigation("SystemUser");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserRefreshToken", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUserDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Worker", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerAvailability", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Availabilities")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerCertificate", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Certificates")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerEducation", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Educations")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerExperience", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Experiences")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerInterestedJobCategory", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("InterestedJobCategories")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCategory");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerLanguage", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Languages")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerPayout", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.ShiftAssignment", "ShiftAssignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("ShiftAssignment");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerReference", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("References")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerSkill", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("Skills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.WorkerSocialLink", b =>
                {
                    b.HasOne("Azoxia.AdaIsAkademi.Domain.Worker", "Worker")
                        .WithMany("SocialLinks")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Employer", b =>
                {
                    b.Navigation("JobPostings");

                    b.Navigation("Locations");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.JobPosting", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUser", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.SystemUserGroup", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Azoxia.AdaIsAkademi.Domain.Worker", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("InterestedJobCategories");

                    b.Navigation("Languages");

                    b.Navigation("References");

                    b.Navigation("Skills");

                    b.Navigation("SocialLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
