<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyName>Azoxia.AdaIsAkademi.Api</AssemblyName>
		<RootNamespace>Azoxia.AdaIsAkademi.Api</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Core\src\Api\Api.csproj" />
		<ProjectReference Include="..\..\..\Core\src\Generators\Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
		<ProjectReference Include="..\Persistence\Persistence.csproj" />
	</ItemGroup>
</Project>